version: '3'

services:
  localstack:
    image: 'localstack/localstack'
    restart: always
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - SERVICES=dynamodb,sqs
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
